### ISSUE TITLE
Fix typo in function name

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/yaclt#130]
In `run-action.ts`, the function `relativeize` should be `relativize`.

**Comment by demonicirfan** [comment]
Hii, can I work on this. I am new to open source and don't have much experience, this will motivate me to contribute towards open source projects.

**Comment by mrjones2014** [comment]
Absolutely! I'll assign you @demonicirfan

**Comment by demonicirfan** [comment]
Thanks for assigning it to me. I have done the pull request.
