### ISSUE TITLE
Make `PrepareReleaseStrategy` an interface instead of an abstract class

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/yaclt#131]
I don't really remember why I originally went down the road of making it an abstract class. I think there was a reason at one point, but it doesn't need to be now. There are only abstract methods in it.

It should be converted to an interface.

**Comment by mrjones2014** [comment]
Basically, in `prepare-release-strategy.ts`, change `export abstract class PrepareReleaseStrategy` to `export interface PrepareReleaseStrategy`, and remove the `abstract` modifier keyword from the methods.

Then, you will have to update the implementations (`with-change-type.ts` and `without-change-type.ts`) and change them from `extends PrepareReleaseStrategy` to `implements PrepareReleaseStrategy`, and remove the `override` keyword from their methods.

**Comment by hsheikhali1** [comment]
Probably want to remove the `super()` call as well since we aren't extending a class anything
