### ISSUE TITLE
Upadate PR template to make sure people are reading the contributing guidelines

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/yaclt#137]
**Is your feature request related to a problem? Please describe.**
When submitting PRs, the templates must be filled out, changelogs must be added, and proper code style must be followed.

**Describe the solution you'd like**
Add the following to the top of the changelog template:

>If you have not contributed before, **please read [CONTRIBUTING.md](https://github.com/mrjones2014/yaclt/blob/master/CONTRIBUTING.md)!**

**Comment by mrjones2014** [comment]
This would go in `pull_request_template.md` at the top.

**Comment by vishal-codes** [comment]
@mrjones2014 Can I work on this?

**Comment by mrjones2014** [comment]
Sure, I'll assign you @vishal-codes

**Comment by mrjones2014** [comment]
Lets surround the text listed in the issue with comment syntax so it only appears in the editor, e.g.

```
<!-- If you have not contributed before, **please read CONTRIBUTING.md (https://github.com/mrjones2014/yaclt/blob/master/CONTRIBUTING.md)!** -->
```

**Comment by vishal-codes** [comment]
> Lets surround the text listed in the issue with comment syntax so it only appears in the editor, e.g.
> 
> ```
> 
> ```

Okaay!

**Comment by vishal-codes** [comment]
Hey @mrjones2014  I entered `yarn build; ./dist/index.js` and this is what I got on the terminal
`00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'build'
bash: ./dist/index.js: No such file or directory
`

**Comment by mrjones2014** [comment]
@vishal-codes is `yarn build` succeeding? try running `yarn build` by itself first. If that fails, `dist/index.js` won't be created.

Are you on Windows, Linux, or MacOS?

**Comment by vishal-codes** [comment]
> @vishal-codes is `yarn build` succeeding? try running `yarn build` by itself first. If that fails, `dist/index.js` won't be created.
> 
> Are you on Windows, Linux, or MacOS?

Linux

**Comment by mrjones2014** [comment]
Hm, the build tooling should work on Linux (I'm not sure about Windows, I don't develop on Windows and can't test it).

Is `yarn build` succeeding?

Did you run `yarn` to install dependencies before trying to build?

**Comment by vishal-codes** [comment]
> Hm, the build tooling should work on Linux (I'm not sure about Windows, I don't develop on Windows and can't test it).
> 
> Is `yarn build` succeeding?
> 
> Did you run `yarn` to install dependencies before trying to build?

When I run `run` I get `00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.`

**Comment by mrjones2014** [comment]
@vishal-codes I'm not sure where you got the `run` command from.

The commands you should be running are:

```shell
yarn
yarn build
./dist/index.js new
```

**Comment by vishal-codes** [comment]
> @vishal-codes I'm not sure where you got the `run` command from.
> 
> The commands you should be running are:
> 
> ```shell
> yarn
> yarn build
> ./dist/index.js new
> ```

Done!!  :)

**Comment by vishal-codes** [comment]
@mrjones2014 As the PR is merged can you close this issue ?
