### ISSUE TITLE
Update bug issue template

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/yaclt#149]
**Is your feature request related to a problem? Please describe.**
The bug issue template has a lot of stuff in it that's not relevant, like smartphone OS info, etc.

**Describe the solution you'd like**
Remove irrelevant prompts.

**Comment by vishal-codes** [comment]
@mrjones2014 are you referring to this <a href="https://github.com/mrjones2014/yaclt/blob/master/.github/ISSUE_TEMPLATE/bug_report.md">bug_report.md</a> ?

**Comment by vishal-codes** [comment]
How about this?

![Screenshot from 2021-09-11 11-48-23](https://user-images.githubusercontent.com/79784161/132938512-414267df-df7b-4028-963d-8a149c429f3c.png)

**Comment by mrjones2014** [comment]
I don’t think we need the table at the top, but other than that, that looks great. The table at the top will be the fields filled in by maintainers after the issue is filed @vishal-codes

**Comment by vishal-codes** [comment]
> I don’t think we need the table at the top, but other than that, that looks great. The table at the top will be the fields filled in by maintainers after the issue is filed @vishal-codes


Okay then I'll start working on this tomorrow as today I am travelling 😅
