### ISSUE TITLE
Allow config files to be "hidden files" (start with a dot)

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/yaclt#164]
**Is your feature request related to a problem? Please describe.**
We should allow, for example, `yacltrc.js` and `.yacltrc.js`, for each format.

**Describe the solution you'd like**
Update the `supportedConfigFilenames` array in `config-handler.ts`. For each option in the array, add another value that's the same but with a leading `.`. The final array should look like:

```ts
const supportedConfigFilenames = [
  "yacltrc.yaml",
  ".yacltrc.yaml",
  "yacltrc.yml",
  ".yacltrc.yml",
  "yacltrc.json",
  ".yacltrc.json",
  "yacltrc.js",
  ".yacltrc.js",
];
```

**Comment by vishal-codes** [comment]
Can I work on this?

**Comment by mrjones2014** [comment]
sure
