### ISSUE TITLE
Add check to `prepare-release` to ensure duplicate release numbers are not added to the changelog

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/yaclt#38]
e.g. if the global `CHANGELOG.md` contains a header

```
# Release 0.4.0
```

And `prepare-release` is run and the `--releaseNumber` is "0.4.0" it should fail because that release has already been generated.

**Comment by mrjones2014** [comment]
this also needs to take into account the fact that the changelog is a customizable template

**Comment by hsheikhali1** [comment]
Do you already parse the `CHANGELOG.md` file ? haven't looked at the code yet but I will

**Comment by mrjones2014** [comment]
Nope haven’t done any parsing of CHANGELOG.md yet

**Comment by mrjones2014** [comment]
closing in favor of #76
