### ISSUE TITLE
remove unused dependencies.

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/yaclt#70]
We aren't actually using `@types/fs-extra`.

`pinst` is not currently used but we should use it. Let's add a `postinstall` script for `husky install`.

![Screen Shot 2021-07-24 at 3 54 28 PM](https://user-images.githubusercontent.com/8648891/126879784-d8bf2761-cf1a-4106-b427-2a6cec1fa148.png)

**Comment by hsheikhali1** [comment]
This a nice easy win :)

**Comment by mrjones2014** [comment]
@hsheikhali1 nit sure why my PR didn’t close it but I already did this

**Comment by hsheikhali1** [comment]
Lol oh okay well that's fine ahaha
