### ISSUE TITLE
Refactor hooks architecture

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/yaclt#79]
Issue here to collect ideas. The current hooks implementation works but is hacky. Rather than single `preHook` and `postHook` functions which get the command name as a parameter, we should have a separate set of hooks for each stage.

Hook arguments will need to be excluded from the `call-function-args.ts` middleware.

@hsheikhali1 any ideas welcome.

**Comment by hsheikhali1** [comment]
how would you determine when we reach a certain stage? Just trying to visualize it

**Comment by mrjones2014** [comment]
a "stage" I'm envisioning as basically, before and after each command handler is executed.

for example, when you run `prepare-release`, it actually implicitly runs `validate` first. So for this case the "order of operations" would be:

- pre-validate
- validate
- post-validate
- pre-generate
- generate
- post-generate

**Comment by hsheikhali1** [comment]
Okay that helps a lot makes more sense
