### ISSUE TITLE
Should we merge local with global config?

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/yaclt#84]
If we find a local config file, e.g. `./yacltrc.yml`, and also a global config file, e.g. `~/.config/yaclt/yacltrc.yml`, should we merge the global config into the local config?

I can see an argument for both "yes" and "no" to this question.

@hsheikhali1 thoughts?

**Comment by hsheikhali1** [comment]
To be honest - all other configuration based tools I've used always overwrote global configurations if it found a local one. Other than that it should just use whatever it finds in`~/.config/yactl/yactlrc.yml`

**Comment by mrjones2014** [comment]
Yeah, I think you're right (do not merge local with global config). Closing.
