### ISSUE TITLE
replace `colors` with `chalk` in the logger

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/yaclt#98]
https://www.npmjs.com/package/chalk

Consider also introducing a proper logging solution.

**Comment by hsheikhali1** [comment]
From what I've used in the past - I highly recommend using Winston :) but if you want a pretty logger with native typescript support this one seems to be popular https://github.com/fullstack-build/tslog.

**Comment by mrjones2014** [comment]
We should add `--verbose` option that prints stack traces and hide them otherwise.
